2023-12-07 03:38:07,836 INFO    MainThread:19296 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2023-12-07 03:38:07,836 INFO    MainThread:19296 [wandb_setup.py:_flush():76] Configure stats pid to 19296
2023-12-07 03:38:07,836 INFO    MainThread:19296 [wandb_setup.py:_flush():76] Loading settings from C:\Users\aman.sa\.config\wandb\settings
2023-12-07 03:38:07,836 INFO    MainThread:19296 [wandb_setup.py:_flush():76] Loading settings from c:\Users\aman.sa\Documents\code\PicfPos\Image classifier\wandb\settings
2023-12-07 03:38:07,837 INFO    MainThread:19296 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-12-07 03:38:07,837 INFO    MainThread:19296 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-12-07 03:38:07,838 INFO    MainThread:19296 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-12-07 03:38:07,839 INFO    MainThread:19296 [wandb_init.py:_log_setup():524] Logging user logs to c:\Users\aman.sa\Documents\code\PicfPos\Image classifier\wandb\run-20231207_033807-i9s0pd00\logs\debug.log
2023-12-07 03:38:07,839 INFO    MainThread:19296 [wandb_init.py:_log_setup():525] Logging internal logs to c:\Users\aman.sa\Documents\code\PicfPos\Image classifier\wandb\run-20231207_033807-i9s0pd00\logs\debug-internal.log
2023-12-07 03:38:07,839 INFO    MainThread:19296 [wandb_init.py:init():564] calling init triggers
2023-12-07 03:38:07,839 INFO    MainThread:19296 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2023-12-07 03:38:07,840 INFO    MainThread:19296 [wandb_init.py:init():589] re-initializing run, found existing run on stack: uvn2sb85
2023-12-07 03:38:07,842 INFO    MainThread:19296 [wandb_run.py:_finish():1962] finishing run amnx/PicfPos/uvn2sb85
2023-12-07 03:38:07,843 ERROR   MainThread:19296 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2023-12-07 03:38:07,844 INFO    MainThread:19296 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-12-07 03:38:07,844 INFO    MainThread:19296 [wandb_init.py:_jupyter_teardown():452] cleaning up jupyter logic
2023-12-07 03:38:07,844 INFO    MainThread:19296 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2023-12-07 03:38:07,844 INFO    MainThread:19296 [wandb_run.py:_restore():2185] restore
2023-12-07 03:38:07,844 INFO    MainThread:19296 [wandb_run.py:_restore():2191] restore done
2023-12-07 03:38:13,976 INFO    MainThread:19296 [wandb_run.py:_footer_history_summary_info():3837] rendering history
2023-12-07 03:38:13,976 INFO    MainThread:19296 [wandb_run.py:_footer_history_summary_info():3869] rendering summary
2023-12-07 03:38:13,980 INFO    MainThread:19296 [wandb_run.py:_footer_sync_info():3796] logging synced files
2023-12-07 03:38:14,793 INFO    MainThread:19296 [wandb_init.py:init():614] starting backend
2023-12-07 03:38:14,793 INFO    MainThread:19296 [wandb_init.py:init():618] setting up manager
2023-12-07 03:38:14,796 INFO    MainThread:19296 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2023-12-07 03:38:14,797 INFO    MainThread:19296 [wandb_init.py:init():624] backend started and connected
2023-12-07 03:38:14,801 INFO    MainThread:19296 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2023-12-07 03:38:14,801 INFO    MainThread:19296 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-12-07 03:38:14,801 INFO    MainThread:19296 [wandb_init.py:init():716] updated telemetry
2023-12-07 03:38:14,852 INFO    MainThread:19296 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2023-12-07 03:38:16,129 INFO    MainThread:19296 [wandb_run.py:_on_init():2254] communicating current version
2023-12-07 03:38:16,643 INFO    MainThread:19296 [wandb_run.py:_on_init():2263] got version response 
2023-12-07 03:38:16,643 INFO    MainThread:19296 [wandb_init.py:init():800] starting run threads in backend
2023-12-07 03:38:21,692 INFO    MainThread:19296 [wandb_run.py:_console_start():2233] atexit reg
2023-12-07 03:38:21,693 INFO    MainThread:19296 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2023-12-07 03:38:21,693 INFO    MainThread:19296 [wandb_run.py:_redirect():2153] Wrapping output streams.
2023-12-07 03:38:21,693 INFO    MainThread:19296 [wandb_run.py:_redirect():2178] Redirects installed.
2023-12-07 03:38:21,694 INFO    MainThread:19296 [wandb_init.py:init():841] run started, returning control to user process
2023-12-07 03:38:21,694 INFO    MainThread:19296 [wandb_watch.py:watch():51] Watching
2023-12-07 03:38:54,647 INFO    MainThread:19296 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2023-12-07 03:38:54,648 INFO    MainThread:19296 [wandb_setup.py:_flush():76] Configure stats pid to 19296
2023-12-07 03:38:54,648 INFO    MainThread:19296 [wandb_setup.py:_flush():76] Loading settings from C:\Users\aman.sa\.config\wandb\settings
2023-12-07 03:38:54,648 INFO    MainThread:19296 [wandb_setup.py:_flush():76] Loading settings from c:\Users\aman.sa\Documents\code\PicfPos\Image classifier\wandb\settings
2023-12-07 03:38:54,648 INFO    MainThread:19296 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-12-07 03:38:54,648 INFO    MainThread:19296 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-12-07 03:38:54,648 INFO    MainThread:19296 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-12-07 03:38:54,649 INFO    MainThread:19296 [wandb_init.py:_log_setup():524] Logging user logs to c:\Users\aman.sa\Documents\code\PicfPos\Image classifier\wandb\run-20231207_033854-oeu14iue\logs\debug.log
2023-12-07 03:38:54,649 INFO    MainThread:19296 [wandb_init.py:_log_setup():525] Logging internal logs to c:\Users\aman.sa\Documents\code\PicfPos\Image classifier\wandb\run-20231207_033854-oeu14iue\logs\debug-internal.log
2023-12-07 03:38:54,649 INFO    MainThread:19296 [wandb_init.py:_jupyter_setup():470] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000019B5B5273D0>
2023-12-07 03:38:54,649 INFO    MainThread:19296 [wandb_init.py:init():564] calling init triggers
2023-12-07 03:38:54,649 INFO    MainThread:19296 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2023-12-07 03:38:54,649 INFO    MainThread:19296 [wandb_init.py:init():589] re-initializing run, found existing run on stack: i9s0pd00
2023-12-07 03:38:54,652 INFO    MainThread:19296 [wandb_run.py:_finish():1962] finishing run amnx/PicfPos/i9s0pd00
2023-12-07 03:38:54,652 INFO    MainThread:19296 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2023-12-07 03:38:54,653 INFO    MainThread:19296 [wandb_run.py:_restore():2185] restore
2023-12-07 03:38:54,653 INFO    MainThread:19296 [wandb_run.py:_restore():2191] restore done
2023-12-07 03:39:01,507 INFO    MainThread:19296 [wandb_run.py:_footer_history_summary_info():3837] rendering history
2023-12-07 03:39:01,507 INFO    MainThread:19296 [wandb_run.py:_footer_history_summary_info():3869] rendering summary
2023-12-07 03:39:01,511 INFO    MainThread:19296 [wandb_run.py:_footer_sync_info():3796] logging synced files
